apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gpt-oss-20b
  labels:
    app: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      runtimeClassName: nvidia
      hostIPC: true
      terminationGracePeriodSeconds: 120
      containers:
        - name: vllm
          image: vllm/vllm-openai:gptoss
          imagePullPolicy: Always
          args:
            - --model
            - openai/gpt-oss-20b
            - --dtype
            - bfloat16
            - --tensor-parallel-size
            - "1"
            - --gpu-memory-utilization
            - "0.90"
            - --download-dir
            - /models
            - --served-model-name
            - gpt-oss-20b
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: NCCL_P2P_LEVEL
              value: "SYS"
            - name: VLLM_LOGGING_LEVEL
              value: "INFO"
            - name: PYTORCH_CUDA_ALLOC_CONF
              value: "expandable_segments:True"
            - name: HF_HOME
              value: /root/.cache/huggingface
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
            - name: models
              mountPath: /models
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              cpu: "2"
              memory: "16Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "8"
              memory: "48Gi"
              nvidia.com/gpu: 1
          readinessProbe:
            httpGet:
              path: /v1/models
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /v1/models
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
      volumes:
        - name: hf-cache
          hostPath:
            path: /home/gpt-oss/.cache/huggingface
            type: DirectoryOrCreate
        - name: models
          hostPath:
            path: /home/gpt-oss/models
            type: DirectoryOrCreate
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "4Gi"
