apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gpt-oss-20b
spec:
  replicas: 1
  selector: { matchLabels: { app: vllm } }
  template:
    metadata: { labels: { app: vllm } }
    spec:
      runtimeClassName: nvidia
      hostIPC: true

      containers:
        - name: vllm
          image: ghcr.io/cloud-linuxer/argocd-apps/vllm:0.1.0-amd64
          imagePullPolicy: Always
          args:
            - --model
            - openai/gpt-oss-20b
            - --max-model-len
            - "12090"
            - --dtype
            - bfloat16
            - --tensor-parallel-size
            - "1"
            - --gpu-memory-utilization
            - "0.90"
            - --download-dir
            - /models
          ports:
            - containerPort: 8000
          env:
            - name: NCCL_P2P_LEVEL
              value: "SYS"
            - name: VLLM_LOGGING_LEVEL
              value: "INFO"
            # Blackwell(5090) 강제
            - name: VLLM_ATTENTION_BACKEND
              value: "FLASHINFER"
            - name: VLLM_USE_FLASHINFER_SAMPLER
              value: "1"
            - name: PYTORCH_CUDA_ALLOC_CONF
              value: "expandable_segments:True"
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
            - name: models
              mountPath: /models
          resources:
            limits:
              nvidia.com/gpu: 1

      volumes:
        - name: hf-cache
          hostPath:
            path: /home/gpt-oss/.cache/huggingface
            type: DirectoryOrCreate
        - name: models
          hostPath:
            path: /home/gpt-oss/models
            type: DirectoryOrCreate
