apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: sumologic/github-actions-runner:latest
        env:
        - name: GITHUB_OWNER
          value: "Cloud-Linuxer"
        - name: GITHUB_REPOSITORY
          value: "argocd-apps"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: token
        volumeMounts:
        - name: k3s-socket
          mountPath: /var/run/k3s
        - name: k3s-bin
          mountPath: /usr/local/bin/k3s
      volumes:
      - name: k3s-socket
        hostPath:
          path: /run/k3s
      - name: k3s-bin
        hostPath:
          path: /usr/local/bin/k3s
