apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    version: "3.0.0"
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30082
  type: NodePort
