name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Harbor
      run: |
        echo "Harbor12345" | docker login localhost:30002 -u admin --password-stdin
    
    - name: Build and Push to Harbor
      run: |
        cd backend
        docker buildx build --platform linux/amd64 \
          -t localhost:30002/library/backend:${{ github.sha }} \
          -t localhost:30002/library/backend:latest \
          --push .
