name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Docker
      run: |
        cd backend
        docker build -t harbor-registry.harbor.svc.cluster.local:5000/library/backend:${{ github.sha }} .
        docker build -t harbor-registry.harbor.svc.cluster.local:5000/library/backend:latest .
    
    - name: Push to Harbor
      run: |
        echo Harbor12345 | docker login harbor-registry.harbor.svc.cluster.local:5000 -u admin --password-stdin --insecure-registry
        docker push harbor-registry.harbor.svc.cluster.local:5000/library/backend:${{ github.sha }}
        docker push harbor-registry.harbor.svc.cluster.local:5000/library/backend:latest
