name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Harbor
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.harbor.svc.cluster.local:80 -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin
    
    - name: Build and Push to Harbor
      run: |
        cd backend
        docker buildx build --platform linux/amd64 \
          -t harbor.harbor.svc.cluster.local:80/library/backend:${{ github.sha }} \
          -t harbor.harbor.svc.cluster.local:80/library/backend:latest \
          --push .
