name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and push to Harbor
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          harbor-registry.harbor.svc.cluster.local:5000/library/backend:${{ github.sha }}
          harbor-registry.harbor.svc.cluster.local:5000/library/backend:latest
        build-args: |
          REGISTRY_AUTH_USERNAME=${{ secrets.HARBOR_USERNAME }}
          REGISTRY_AUTH_PASSWORD=${{ secrets.HARBOR_PASSWORD }}
