name: Backend Build and Push
on:
  push:
    paths: ['backend/**']
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: prep
        shell: bash
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}/backend" >> "$GITHUB_OUTPUT"
             echo "iamge=${GITHUB_REPOSITORY,,}"

      - name: Get version from app.py
        id: version
        run: |
          VERSION=$(grep -o '"version": "[^"]*"' backend/app.py | cut -d'"' -f4)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }}
            ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }}-amd64
            ${{ steps.prep.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image push
        run: |
          echo "Verifying image was pushed successfully..."
          docker run --rm gcr.io/go-containerregistry/crane:debug \
            manifest ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }} || echo "Failed to verify image"
