name: Backend Build and Push
on:
  push:
    paths: ['backend/**']
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      REGISTRY: harbor.local:30003   # Harbor externalURL(HTTPS)
    steps:
      - uses: actions/checkout@v4

      - name: Setup Harbor CA certificate
        run: |
          sudo mkdir -p /etc/docker/certs.d/harbor.local:30003
          kubectl get secret -n harbor harbor-tls -o jsonpath='{.data.ca\.crt}' | base64 -d | sudo tee /etc/docker/certs.d/harbor.local:30003/ca.crt

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/library/backend:${{ github.sha }}
            ${{ env.REGISTRY }}/library/backend:latest
