name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_AUTH_CONFIG: >
        {"auths":{"harbor-registry.harbor.svc.cluster.local:5000":{
          "username":"${{ secrets.HARBOR_USERNAME }}",
          "password":"${{ secrets.HARBOR_PASSWORD }}"}}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."harbor-registry.harbor.svc.cluster.local:5000"]
              http = true
              insecure = true

      - name: Build and push to Harbor
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            harbor-registry.harbor.svc.cluster.local:5000/library/backend:${{ github.sha }}
            harbor-registry.harbor.svc.cluster.local:5000/library/backend:latest
