name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Docker
      run: |
        cd backend
        docker build -t harbor-registry.harbor.svc.cluster.local:5000/library/backend:${{ github.sha }} .
        docker build -t harbor-registry.harbor.svc.cluster.local:5000/library/backend:latest .
    
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor-registry.harbor.svc.cluster.local:5000
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        insecure: true
    
    - name: Push to Harbor
      run: |
        docker push harbor-registry.harbor.svc.cluster.local:5000/library/backend:${{ github.sha }}
        docker push harbor-registry.harbor.svc.cluster.local:5000/library/backend:latest
