name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Harbor
      run: |
        docker login harbor.harbor.svc.cluster.local -u admin -p Harbor12345
    
    - name: Build and Push to Harbor
      run: |
        cd backend
        docker buildx build --platform linux/amd64 \
          -t harbor.harbor.svc.cluster.local/library/backend:${{ github.sha }} \
          -t harbor.harbor.svc.cluster.local/library/backend:latest \
          --push .
