name: Backend Build and Push

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [registry."harbor.harbor.svc.cluster.local"]
            http = false
            insecure = true
    
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.harbor.svc.cluster.local
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    
    - name: Build and push to Harbor
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          harbor.harbor.svc.cluster.local/library/backend:${{ github.sha }}
          harbor.harbor.svc.cluster.local/library/backend:latest
