name: Backend Build and Push
on:
  push:
    paths: ['backend/**']
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: prep
        shell: bash
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}/backend" >> "$GITHUB_OUTPUT"

      - name: Get version from app.py
        id: version
        run: |
          VERSION=$(grep -o '"version": "[^"]*"' backend/app.py | cut -d'"' -f4)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx (multiplatform)
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          driver-opts: |
            network=host

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }}
            ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }}-amd64
            ${{ steps.prep.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
