name: Backend Build and Push

on:
  push:
    paths: ['backend/**']
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # ghcr.io/<owner>/<repo>/backend  (모두 소문자 강제)
      - name: Compute image name (lowercase)
        id: prep
        shell: bash
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}/backend"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:${{ github.sha }}
            ${{ steps.prep.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
