name: vLLM Build and Push
on:
  push:
    paths: ['vllm/**']
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: prep
        shell: bash
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}/vllm" >> "$GITHUB_OUTPUT"

      - name: Get version
        id: version
        run: |
          VERSION=$(cat vllm/VERSION)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./vllm
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }}-amd64
            ${{ steps.prep.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update manifest
        run: |
          sed -i "s|image: ghcr.io/.*/vllm:.*|image: ${{ steps.prep.outputs.image }}:${{ steps.version.outputs.version }}-amd64|g" manifests/vllm-20b/deployment.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifests/vllm-20b/deployment.yaml
          git commit -m "Update vllm image to ${{ steps.version.outputs.version }}" || exit 0
          git push
